# -*- coding: utf-8 -*-
"""Entropy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hmLGwTqVb1iSvtgJxMM6fhaynePnMIy7
"""

import math
import numpy as np
import seaborn as sns
import random
import pandas as pd
import matplotlib.pyplot as plt

"""#Shannon Diversity
Shannon Diversity, or entropy measure uncertainty

$$H(X) = \sum_{x \in X} p(x_i)log_2(p(x_i))$$
"""

def entropy(probs):
  # Auto-correct by adding the missing probability if total < 1
  total = sum(probs)

  if total < 1.0:
    missing = 1.0 - total
    probs.append(missing)
  elif total > 1.0:
    raise ValueError("Probabilities sum to more than 1")

 # Calculates Entropy
  value=0
  for p in probs:
    if p != 0:
      value += p * math.log2(p)

  return -value

# Simulate sample size 10, 20, 50, 100, 200
# Simulate the expected frequencies of 0.1, 0.2, 0.5
# Simulate the binomial counts 10 times
# Calculated the Shanon Diversity (Entropy)
# Plot Mean and Standard Error

entropy([0.2, 0.3, 0.1, 0.4])

p = np.arange(0,1.1,0.1)
float(p[1])
ent=[]
for i in p:
  ent.append(entropy([i,1.0-i]))

ent

sns.scatterplot(x=p,y=ent)

def ent_avg(prob,size):
  ent_lis = []
  for times in range(10):

    sample_x= random.choices([0,1], weights=[prob,1-prob],k=size)
    sample_x

    one = 0
    for g in sample_x:
      if g == 1:
        one += 1
    length = len(sample_x)
    freq_1 = one/length
    freq_0= (length - one)/ length
    #print(freq_1)
    #print(freq_0)
    ent_lis.append(entropy([freq_0,freq_1]))

  ent_arr = np.array(ent_lis)
  return np.mean(ent_arr)
#std_error = np.std(ent_arr,ddof=1) / np.sqrt(len(ent_lis))
#std_error

def line_points(prob):
  mean_lis = []
  size_lis = [10, 20, 50, 100, 200]
  for size in size_lis :
    mean_lis.append(ent_avg(prob, size))

  return mean_lis

# Making the Line Plot

sample_sizes = [10, 20, 50, 100, 200]
mean_entropy_01 = line_points(0.1)
mean_entropy_02 = line_points(0.2)
mean_entropy_05 = line_points(0.5)


data = pd.DataFrame({
    'sample_size': sample_sizes * 3,
    'mean_entropy': mean_entropy_01 + mean_entropy_02 + mean_entropy_05,
    'frequency': ['0.1'] * 5 + ['0.2'] * 5 + ['0.5'] * 5
})



sns.lineplot(
    data=data,
    x='sample_size',
    y='mean_entropy',
    hue='frequency',
    style='frequency',
    markers=True,
    dashes=False
)
#plt.errors(x= , y= )

plt.title("Shanon Diversity over different Frequencies")
plt.xlabel("Sample Size")
plt.ylabel("Shannon Diversity")
plt.legend(title="Frequency")
plt.show()

def ent_vec(data):
  freq = data.count(1)
  freq = freq / len(data)
  return entropy([freq])

ent_vec([1,0,1,1])

"""#Joint Entropy

$$H(X,Y)= -\sum_{(x,y) \in (X,Y)} p(x,y)log_2(p(x,y)) $$
"""

def joint_e (prob, size):
  samp_x = random.choices([0,1], weights = [prob, 1-prob], k=size)

  samp_y = random.choices([0,1], weights = [prob, 1-prob], k=size)

  data = pd.DataFrame({'X': samp_x, 'Y' : samp_y})
  print(samp_x)
  print(samp_y)
  p_dist = pd.crosstab(data['X'], data['Y'], normalize = 'all')
  print(p_dist)
  p_dist = p_dist.values.tolist()
  j_entropy = 0.0
  for row in p_dist:
    for p in row:
      if p > 0:
        j_entropy -= p * math.log2(p)




  return j_entropy

def JointFreq(sampx, sampy):
  pairs = list(zip(sampx, sampy))
  freq = {}
  freq [(1, 0)] = pairs.count((1, 0)) / len(pairs)
  freq [(0, 0)] = pairs.count((0, 0)) / len(pairs)
  freq [(0, 1)] = pairs.count((0, 1)) / len(pairs)
  freq [(1, 1)] = pairs.count((1, 1)) / len(pairs)


  return freq

def joint_ent (samp_x, samp_y):


  j_freq = JointFreq(samp_x, samp_y)

  j_entropy = 0.0
  for key in j_freq.keys():
    if j_freq[key] > 0:
      j_entropy -= j_freq[key] * math.log2(j_freq[key])




  return j_entropy

samp1 = random.choices([1,0], weights=[.5,.7], k=10)
samp2 = random.choices([1,0], weights=[.3,.7], k=10)
pairs = list(zip(samp1, samp2))
pairs



freq = {}
freq [(1,0)] = pairs.count((1,0))/len(pairs)
freq [(0,0)] = pairs.count((0,0))/len(pairs)



freq

#freq1 = pairs.count((1,0))/len(pairs)

#freq1

#freq0 = 1-freq1
#[freq1, freq0]

def freq(sampx):
  fre = {}
  fre [1] = sampx.count(1) / len(sampx)
  fre [0] = sampx.count(0) / len(sampx)

  return fre

jf = JointFreq(samp1, samp2)
#freq(samp1)

#for i in jf.keys():
  #print(jf[i])



joint_ent(samp1, samp2)

"""#Mutual Information - Raw and Standardized

$MI_n(X_n;Y_n) = H(X_n) + H(Y_n) - H(X_n,Y_n) $ Raw MI


$MIR_n =\frac{MI_n}{min(H(X_n), H(Y_n)}$ Standardized MI
"""

def MIR(sampx, sampy):
  MI = ent_vec(sampx) + ent_vec(sampy) - joint_ent(sampx, sampy)


  m = min(ent_vec(sampx), ent_vec(sampy))

  MIR = MI/m

  return MIR

samp1 = random.choices([1,0], weights=[.5,.5], k=100)
samp2 = random.choices([1,0], weights=[.5,.5], k=100)
MIR(samp1, samp2)

"""#Measuring Linkage with D and D'
$D= P(AB) - P(A) P(B)$    A=1 a=0 , B=1, a = 1


$D' = \frac{D}{min(P(A) * P(b), P(a) * P(B)))} if D>0 $

$D' = \frac{D}{max(-P(A) * P(B), -P(a) * P(b)} if D<0 $

$r^2 = \frac{D}{P(A) P(a) P(B) P(b)}$

Like entropy, D is measure of independence of Alleles between sites.
"""

def D_prime(samp1, samp2):

  freq_xy = JointFreq(samp1, samp2)
  freq_x = freq(samp1)
  freq_y = freq(samp2)

  D = freq_xy[(1,1)] - freq_x[(1)] * freq_y[(1)]

  if D > 0:
    D_p = D / min(freq_x[(1)] * freq_y[(0)], freq_x[(0)] * freq_y[(1)])
  else:
    D_p = D / max(-freq_x[(1)] * freq_y[(1)], -freq_x[(0)] * freq_y[(0)])

  return D_p

D_prime(samp1, samp2)

import numpy as np
from scipy.stats import norm, binom

#input:  sample_size and r the correlation coefficient
#output: two binary vectors of size sample_size with correlation approx r.
def createBinaryList(sample_size,r):
  z = np.random.randn(2, sample_size)
  #print(z)
  if 0<r and r<1:
    my_list = [1,r,r,1]
    sigma = np.array(my_list).reshape(2,2)
    s = np.linalg.cholesky(sigma)    #for symmetric matrices cholesky does a outputs a lower triangular matrix. s=Lower.Upper o
    z = np.dot(s,z)
  #print(z)

  u = norm.cdf(z)  # translates the CDF elementwise, returning a matrix of probabilities.  F(z_ij)=P(Z<=z_ij)
  row_probs = u[0, :]
  quantiles = binom.ppf(row_probs,n=1,p=0.5)
  site1 = quantiles
  site2 = site1
  if r < 1:
    row_probs = u[1, :]
    quantiles = binom.ppf(row_probs,n=1,p=0.5)
    site2 = quantiles
  return [r,site1,site2]

createBinaryList(10,.9)

def sim(samp_size, r):
  avgMIR = []
  stderrMirr = []
  avgDP = []
  stderrDP = []
  for rep in r:
    MIR_lis = []
    DP_lis = []
    for i in range(10):
      data = createBinaryList(samp_size, rep)
      sampx = data[1].tolist()
      sampy = data[2].tolist()
      MIR_lis.append(MIR(sampx, sampy))
      DP_lis.append(D_prime(sampx, sampy))


    avgMIR.append(np.mean(np.array(MIR_lis)))
    stderrMirr.append(np.std(np.array(MIR_lis)) / np.sqrt(samp_size))

    avgDP.append(np.mean(np.array(DP_lis)))
    stderrDP.append(np.std(np.array(DP_lis))/ np.sqrt(samp_size))

  return avgMIR, stderrMirr, avgDP, stderrDP

r = np.arange(0, 1.1, 0.1)
avgMIR, stderrMirr, avgDP, stderrDP = sim(1000,r)



df = pd.DataFrame({
    "r": np.concatenate([r, r]),
    "value": np.concatenate([avgMIR, avgDP]),
    "std": np.concatenate([stderrMirr, stderrDP]),
    "metric": ["MIR"] * len(r) + ["D'"] * len(r)
    })

plt.figure(figsize=(8, 5))
sns.lineplot(data=df, x="r", y="value", hue="metric", err_style="bars", legend=True)


for metric in df["metric"].unique():
    subset = df[df["metric"] == metric]
    plt.errorbar(subset["r"], subset["value"], yerr=subset["std"], fmt='none', capsize=4)

plt.xlabel("Correlation (r)")
plt.ylabel("Average Value")
plt.title("Average MIR and D' with Error Bars")
plt.grid(True)
plt.tight_layout()
plt.show()
