# -*- coding: utf-8 -*-
"""Entropy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hmLGwTqVb1iSvtgJxMM6fhaynePnMIy7
"""

import math
import numpy as np
import seaborn as sns
import random
import pandas as pd
import matplotlib.pyplot as plt

"""#Shannon Diversity
Shannon Diversity, or entropy measure uncertainty

$$H(X) = \sum_{x \in X} p(x_i)log_2(p(x_i))$$
"""

def entropy(probs):
  # Auto-correct by adding the missing probability if total < 1
  total = sum(probs)

  if total < 1.0:
    missing = 1.0 - total
    probs.append(missing)
  elif total > 1.0:
    raise ValueError("Probabilities sum to more than 1")

 # Calculates Entropy
  value=0
  for p in probs:
    if p != 0:
      value += p * math.log2(p)

  return -value

# Simulate sample size 10, 20, 50, 100, 200
# Simulate the expected frequencies of 0.1, 0.2, 0.5
# Simulate the binomial counts 10 times
# Calculated the Shanon Diversity (Entropy)
# Plot Mean and Standard Error

entropy([0.2, 0.3, 0.1, 0.4])

p = np.arange(0,1.1,0.1)
float(p[1])
ent=[]
for i in p:
  ent.append(entropy([i,1.0-i]))

ent

sns.scatterplot(x=p,y=ent)

def ent_avg(prob,size):
  ent_lis = []
  for times in range(10):

    sample_x= random.choices([0,1], weights=[prob,1-prob],k=size)
    sample_x

    one = 0
    for g in sample_x:
      if g == 1:
        one += 1
    length = len(sample_x)
    freq_1 = one/length
    freq_0= (length - one)/ length
    #print(freq_1)
    #print(freq_0)
    ent_lis.append(entropy([freq_0,freq_1]))

  ent_arr = np.array(ent_lis)
  return np.mean(ent_arr)
#std_error = np.std(ent_arr,ddof=1) / np.sqrt(len(ent_lis))
#std_error

def line_points(prob):
  mean_lis = []
  size_lis = [10, 20, 50, 100, 200]
  for size in size_lis :
    mean_lis.append(ent_avg(prob, size))

  return mean_lis

# Making the Line Plot

sample_sizes = [10, 20, 50, 100, 200]
mean_entropy_01 = line_points(0.1)
mean_entropy_02 = line_points(0.2)
mean_entropy_05 = line_points(0.5)


data = pd.DataFrame({
    'sample_size': sample_sizes * 3,
    'mean_entropy': mean_entropy_01 + mean_entropy_02 + mean_entropy_05,
    'frequency': ['0.1'] * 5 + ['0.2'] * 5 + ['0.5'] * 5
})



sns.lineplot(
    data=data,
    x='sample_size',
    y='mean_entropy',
    hue='frequency',
    style='frequency',
    markers=True,
    dashes=False
)
plt.errors(x= , y= )

plt.title("Shanon Diversity over different Frequencies")
plt.xlabel("Sample Size")
plt.ylabel("Shannon Diversity")
plt.legend(title="Frequency")
plt.show()

"""#Joint Entropy

$$H(X,Y)= -\sum_{(x,y) \in (X,Y)} p(x,y)log_2(p(x,y)) $$
"""

def joint_ent (prob):
  samp_x = random.choices([0,1], weights = [prob, 1-prob], k=10)

  samp_y = random.choices([0,1], weights = [prob, 1-prob], k=10)

  data = pd.DataFrame({'X': samp_x, 'Y' : samp_y})

  p_dist = pd.crosstab(data['X'], data['Y'], normalize = 'all')
  p_dist = p_dist.values.tolist()
  j_entropy = 0.0
  for row in p_dist:
    for p in row:
      if p > 0:
        j_entropy -= p * math.log2(p)




  return j_entropy

joint_ent(0.1)
