# -*- coding: utf-8 -*-
"""Translating_DNA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L-ad8ijgAlL49IC6Vd1rkM5gXgO2bXSj
"""

import pandas as pd
import numpy as np
import re
import math
import matplotlib.pyplot as plt
!pip install biopython
from Bio import SeqIO

codonsTable = pd.read_csv("/content/codonaa.csv")
gc = pd.DataFrame(codonsTable.values.tolist())
gc

"""SwapTU Function, the initial function necessary for reading dna strands as amino acids."""

def SwapTU(dna):
  dna = dna.upper()
  dna = re.sub("T", "U", dna)
  return dna

"""Reversing DNA function for negative frames"""

def ReverseComplement(dna):
  reversedString = ""
  dna.upper()
  for i in range(len(dna)):
    reversedString += dna[len(dna)-i-1]
  newString = ""
  for i in range(len(dna)):
    if reversedString[i] == "A":
      newString += "U"
    if reversedString[i] == "U":
      newString += "A"
    if reversedString[i] == "G":
      newString += "C"
    if reversedString[i] == "C":
      newString += "G"
  return newString

def Translation(dna, start):
   AmAcid = ""
   for x in range(start-1, len(dna)-2, 3):
      element = dna[x:(x + 3)]
      first_index = gc[gc[0] == element].index[0]
      AmAcid += gc.iloc[first_index,1]
   return AmAcid

def readDNA(file):
 for seq_record in SeqIO.parse(file, "fasta"):
    seq = (str(seq_record.seq))
 return  seq

"""Input should be a Fasta File, and the string and should output a string ATGAAAAAGAATACATTAAGTGCAATATTAATGACTTTATTTTTATTTATATCTTGTAATAATTCAGGGAAAGATGGGAATACATCTGCAAATTCTGCTGATGAGTCTGTTAAAGGGCCTAATCTTACAGAAATAAGTAAAAAAATTACGGATTCTAATGCGGTTTTACTTGCTGTGAAAGAGGTTGAAGCGTTGCTGTCATCTATAGATGAAATTGCTGCTAAAGCTATTGGTAAAAAAATACACCAAAATAATGGTTTGGATACCGAAAATAATCACAATGGATCATTGTTAGCGGGAGCTTATGCAATATCAACCCTAATAAAACAAAAATTAGATGGATTGAAAAATGAAGGATTAAAGGAAAAAATTGATGCGGCTAAGAAATGTTCTGAAACATTTACTAATAAATTAAAAGAAAAACACACAGATCTTGGTAAAGAAGGTGTTACTGATGCTGATGCAAAAGAAGCCATTTTAAAAACAAATGGTACTAAAACTAAAGGTGCTGAAGAACTTGGAAAATTATTTGAATCAGTAGAGGTCTTGTCAAAAGCAGCTAAAGAGATGCTTGCTAATTCAGTTAAAGAGCTTACAAGCCCTGTTGTGGCAGAAAGTCCAAAAAAACCTTAA"""

def DnaTranslation(dna, frame):
  dna = SwapTU(dna) #replaces lowercase letters with uppercase letters and then swaps all T's with U's
  AmAcid = ""
  if frame < 0:
    x = abs(frame)
    dna = ReverseComplement(dna) # if frame is negative you need to reverse the strand before you begin reading the frame
    AmAcid = Translation(dna, x)
    return AmAcid
  elif frame > 0:
    AmAcid = Translation(dna, frame)
    return AmAcid

"""Make a Plot/Graphic of the Six Frames, Plot the position of the Stop Coddon and mark with an X and others with a dash, I'll be given a real gene sequence, 6 Lines of dashes and X's.


"""

DnaTranslation(readDNA("sequence.fasta"), 1)

def Visual(file):
  xDash = []
  xX = []
  yDash = []
  yX = []
  for i in range(-3, 4, 1):
    if i != 0:
      Protein = DnaTranslation(readDNA(file), i)
      for z in range(len(Protein)):
        letter = Protein[z]
        if letter == "*":
          xX.append(z)
          yX.append(i)
        elif letter != "*":
          xDash.append(z)
          yDash.append(i)
    elif i == 0:
      continue
  plt.scatter(xX, yX, marker='x', color='blue', label='Data Points')
  plt.scatter(xDash, yDash, marker = "_", color ='red',)
  return plt

Visual("sequence.fasta")
