# -*- coding: utf-8 -*-
"""Information_Theory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RaTM7HCo6CLf4HUDRW3rfE4F5cldL6-O
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math
import random

"""#Entropy
$H(X) = -\sum_{x\in X}p(x_i)log_2 (p(x_i))$
"""

def entropy(prob):
  p1 = prob
  p2 = 1 - prob
  if p1 == 0 or p2 == 0:
    return 0
  ent = -((p1 * math.log2(p1)) + (p2 * math.log2(p2)))
  return ent

entropy(0.1)

probs = np.arange(0.0, 1.1, 0.1)
ent = []
for i in (probs):
  ent.append(entropy(i))
sns.scatterplot(x = probs, y = ent)

def entropyPop(prob, sample_size):
  pop_sample = random.choices([0, 1], weights = [prob, 1 - prob], k = sample_size)
  return entropy(pop_sample.count(1)/sample_size)

sample_sizes = [10, 50, 100, 300]
prob = [0.1, 0.2, 0.5]
sim ={}
sim["sample_sizes"] = []
sim["prob"] =[]
sim["avgEntropy"] = []
sim["stdError"]  =  []
for i in range(len(sample_sizes)):
  for y in range(len(prob)):
    sim["sample_sizes"].append(sample_sizes[i])
    sim["prob"].append(prob[y])
    entropyList = []
    for x in range(0, 10):
      entropyList.append(entropyPop(prob[y], sample_sizes[i]))
    sim["avgEntropy"].append(np.mean(entropyList))
    sim["stdError"].append(np.std(entropyList,ddof=1)/np.sqrt(len(entropyList)))
df = pd.DataFrame(sim)
sns.lineplot(x= df["sample_sizes"],  y=df["avgEntropy"] , hue = df["prob"])
plt.errorbar(df["sample_sizes"], df["avgEntropy"], yerr = df["stdError"], fmt='o', color='gray', capsize=5, linestyle='None')
plt.xlabel('Sample Size')
plt.ylabel('Mean Entropy')
plt.title('Entropy with Standard Error')
plt.legend()
plt.tight_layout()
plt.show()

link = {}
link["locus1"] = random.choices([1,0], weights = [0.3,0.7], k = 10)
link["locus2"] = random.choices([1,0], weights = [0.3,0.7], k = 10)

df = pd.DataFrame(link)
df
#row = each member of your sample population
#col = each col represents locus or site on DNA
#0 = ancestral state
#1 = mutated state

samp_x = random.choices([1,0], weights = [0.3,0.7], k = 10)
def freq(samp_pop):
  count1 = samp_pop.count(1)
  samp_size = len(samp_pop)
  freq1 = count1/samp_size
  return freq1
entropy(freq(samp_x))

"""#Joint Entropy
$H(X,Y) = -\sum_{x,y}p(x,y)log_2(p(x,y)) $
"""

def combineTwoLists(samp_pop1, samp_pop2):
 if len(samp_pop1) == len(samp_pop2):
  ListT = []
  for i in range(len(samp_pop1)):
    ListT.append((samp_pop1[i], samp_pop2[i]))
  return ListT

def sumLog(int):
  if int == 0:
    return 0
  return (int * math.log2(int))

def JointEntropy(samp_pop1, samp_pop2):
    x = combineTwoLists(samp_pop1, samp_pop2)
    p1 = x.count((0,0))/len(samp_pop1)
    p2 = x.count((0,1))/len(samp_pop1)
    p3 = x.count((1,0))/len(samp_pop1)
    p4 = x.count((1,1))/len(samp_pop1)
    return -((sumLog(p1)) + sumLog(p2) + sumLog(p3) + sumLog(p4))

JointEntropy(random.choices([1,0], weights = [0.3,0.7], k = 10),  random.choices([1,0], weights = [0.3,0.7], k = 10))

"""#Mutual Information
MI(X,Y) = H(X) + H(Y) - H(X,Y)
**input**: Two binary lists of the same length representing allele at two loci
**output**: MI(List1, List2)

H(X) = ent, H(Y) = ent, H(X,Y) = Joint ent
"""

def MutualInformationStandard(samp_pop1, samp_pop2):
  ent1 = entropy(freq(samp_pop1))
  ent2 = entropy(freq(samp_pop2))
  J_ent = JointEntropy(samp_pop1, samp_pop2)
  Mut_Inf = ent1 + ent2 - J_ent
  MIR = Mut_Inf/min(ent1,ent2)
  return MIR

MutualInformationStandard(random.choices([1,0], weights = [0.3,0.7], k = 1000),  random.choices([1,0], weights = [0.3,0.7], k = 1000))

import numpy as np
from scipy.stats import norm, binom

#input:  sample_size and r the correlation coefficient
#output: two binary vectors of size sample_size with correlation approx r.
def createBinaryList(sample_size,r):
  z = np.random.randn(2, sample_size)
  #print(z)
  if 0<r and r<1:
    my_list = [1,r,r,1]
    sigma = np.array(my_list).reshape(2,2)
    s = np.linalg.cholesky(sigma)    #for symmetric matrices cholesky does a outputs a lower triangular matrix. s=Lower.Upper o
    z = np.dot(s,z)
  #print(z)

  u = norm.cdf(z)  # translates the CDF elementwise, returning a matrix of probabilities.  F(z_ij)=P(Z<=z_ij)
  row_probs = u[0, :]
  quantiles = binom.ppf(row_probs,n=1,p=0.5)
  site1 = quantiles
  site2 = site1
  if r < 1:
    row_probs = u[1, :]
    quantiles = binom.ppf(row_probs,n=1,p=0.5)
    site2 = quantiles
  return [r,site1,site2]

createBinaryList(10,.9)

binLists = createBinaryList(1000,0.5)
MutualInformationStandard(binLists[1].tolist(), binLists[2].tolist())

"""#Detecting Linkage with $D' \text{and } r^2 $
$D = P(AB) - P(A)*P(B)

$D' = \frac{D}{min(P(A)*P(b),(a)*P(B)}$ $ \text { if } D>0 $

$D' = \frac{D}{max(-P(A)*P(B),-P(a)*P(b))}$ $\text { if } D<0 $
"""

def Dprime(samp_pop1, samp_pop2):
  freq_x1 = samp_pop1.count(1)/len(samp_pop1)
  freq_x0 = samp_pop1.count(0)/len(samp_pop1)
  freq_y1 = samp_pop2.count(1)/len(samp_pop2)
  freq_y0 = samp_pop2.count(0)/len(samp_pop2)
  combList = combineTwoLists(samp_pop1, samp_pop2)
  freq_xy11 = combList.count((1,1))/len(combList)
  D = ((freq_xy11) - (freq_x1)*(freq_y1))
  if D > 0:
    Dp = D/(min((freq_x1)*(freq_y0), (freq_x0)*(freq_y1)))
  if D < 0:
    Dp = D/(max(-(freq_x1)*(freq_y1), -(freq_x0)*(freq_y0)))
  return Dp

seq = np.arange(0, 1.1, 0.1)
avgMIR = []
avgDP = []
stderrMIR = []
stderrDP = []
for x in range(len(seq)):
  entlist = []
  dplist = []
  for y in range(10):
    samps = createBinaryList(1000, r = seq[x])
    samp_pop1 = samps[1].tolist()
    samp_pop2 = samps[2].tolist()
    entlist.append(MutualInformationStandard(samp_pop1, samp_pop2))
    dplist.append(Dprime(samp_pop1, samp_pop2))
  avgMIR.append(np.mean(entlist))
  stderrMIR.append(np.std(entlist)/np.sqrt(10))
  avgDP.append(np.mean(dplist))
  stderrDP.append(np.std(dplist)/np.sqrt(10))

sns.lineplot(x = seq, y = avgMIR)
sns.lineplot(x = seq, y = avgDP)
plt.errorbar(seq, avgMIR, yerr = stderrMIR, fmt='o', color='gray', capsize=5, linestyle='None')
plt.errorbar(seq, avgDP, yerr = stderrDP, fmt='o', color='gray', capsize=5, linestyle='None')
